import car1 from "@assets/images/car1.png";
import benz2 from "@assets/images/benz2.png";
import bmw from "@assets/images/bmw.png";
import audi from "@assets/images/audi.png";
import toyota from "@assets/images/toyota.png";
import nissan from "@assets/images/nissan.png";
import mazda from "@assets/images/mazda.png";
import benz from "@assets/images/benz.png";

export const mockFavorites = [
  {
    id: 1,
    image: car1,
    brand: "Mercedes-Benz",
    model: "C Class",
    description: "2023 C300e AMG Line Night Ed Premium Plus 5dr 9G-Tronic",
    mileage: "72,925 km",
    fuel: "Бензин",
    transmission: "Авто",
    year: 2023,
    price: "$39 900",
  },
  {
    id: 2,
    image: benz2,
    brand: "Mercedes-Benz",
    model: "E Class",
    description: "2024 E300 AMG Line Premium Plus 4dr 9G-Tronic",
    mileage: "45,000 km",
    fuel: "Бензин",
    transmission: "Авто",
    year: 2024,
    price: "$52 000",
  },
  {
    id: 3,
    image: bmw,
    brand: "BMW",
    model: "5 Series",
    description: "2022 530e M Sport 4dr Auto",
    mileage: "58,300 km",
    fuel: "Гибрид",
    transmission: "Авто",
    year: 2022,
    price: "$45 500",
  },
  {
    id: 4,
    image: audi,
    brand: "Audi",
    model: "A4",
    description: "2024 A4 45 TFSI Quattro S Line 4dr S Tronic",
    mileage: "12,000 km",
    fuel: "Бензин",
    transmission: "Авто",
    year: 2024,
    price: "$48 900",
  },
  {
    id: 5,
    image: toyota,
    brand: "Toyota",
    model: "Camry",
    description: "2023 Camry 2.5L VVT-i Hybrid Excel 4dr CVT",
    mileage: "35,200 km",
    fuel: "Гибрид",
    transmission: "Авто",
    year: 2023,
    price: "$32 900",
  },
  {
    id: 6,
    image: nissan,
    brand: "Nissan",
    model: "Qashqai",
    description: "2023 Qashqai 1.3 DiG-T MH Tekna 5dr DCT",
    mileage: "28,500 km",
    fuel: "Бензин",
    transmission: "Авто",
    year: 2023,
    price: "$29 900",
  },
  {
    id: 7,
    image: mazda,
    brand: "Mazda",
    model: "CX-5",
    description: "2024 CX-5 2.5 Skyactiv-G GT Sport 5dr Auto AWD",
    mileage: "8,900 km",
    fuel: "Бензин",
    transmission: "Авто",
    year: 2024,
    price: "$38 500",
  },
  {
    id: 8,
    image: benz,
    brand: "Mercedes-Benz",
    model: "GLC",
    description: "2023 GLC 300 4MATIC AMG Line Premium 5dr 9G-Tronic",
    mileage: "22,100 km",
    fuel: "Бензин",
    transmission: "Авто",
    year: 2023,
    price: "$55 900",
  },
];